# Generated by Django 4.2.20 on 2025-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEconomicIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('cpi', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('federal_funds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('treasury_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='monthly_indicator_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialNewsAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('open_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('volume', models.IntegerField()),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyNewsAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('exchange_rate', models.FloatField()),
                ('last_refreshed', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'last_refreshed')},
            },
        ),
        migrations.CreateModel(
            name='AnnualEconomicIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('real_gdp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('inflation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='annual_indicator_date_idx')],
            },
        ),
    ]
