# Generated by Django 4.2.20 on 2025-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyEvent',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['base', 'target'], name='myapp_curre_base_7993a7_idx'), models.Index(fields=['timestamp'], name='myapp_curre_timesta_a7cd3f_idx')],
            },
        ),
    ]
