# Generated by Django 5.1.7 on 2025-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyEvent',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['base', 'target'], name='myapp_curre_base_7993a7_idx'), models.Index(fields=['timestamp'], name='myapp_curre_timesta_a7cd3f_idx')],
            },
        ),
    ]
