# Generated by Django 4.2.20 on 2025-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyNews',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('exchange_rate', models.FloatField()),
                ('last_refreshed', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'last_refreshed')},
            },
        ),
        migrations.DeleteModel(
            name='CurrencyEvent',
        ),
    ]
