# Generated by Django 4.2.20 on 2025-03-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEconomicIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('cpi', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('federal_funds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('treasury_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='monthly_indicator_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnualEconomicIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('real_gdp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('inflation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='annual_indicator_date_idx')],
            },
        ),
    ]
