# Generated by Django 4.2.20 on 2025-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyNewsAlphaV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('relevance_score', models.FloatField()),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialNewsAlphaV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('relevance_score', models.FloatField()),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.DeleteModel(
            name='CurrencyNewsAlpha',
        ),
        migrations.DeleteModel(
            name='FinancialNewsAlpha',
        ),
    ]
