# Generated by Django 4.2.20 on 2025-03-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyEvent',
        ),
    ]
