# Generated by Django 4.2.20 on 2025-03-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currencynewsalphav_financialnewsalphav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencynewsalphav',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='financialnewsalphav',
            name='relevance_score',
        ),
    ]
