# Generated by Django 4.2.20 on 2025-03-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currencynews'),
        ('myapp', '0003_remove_currency_event'),
    ]

    operations = [
    ]
