# Generated by Django 4.2.20 on 2025-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_currencynewsalphav_relevance_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('target', models.CharField(max_length=3)),
                ('alert_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('threshold', models.DecimalField(decimal_places=6, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
