# Generated by Django 4.2.20 on 2025-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_exchangeratealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratealert',
            name='alert_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
