# Generated by Django 4.2.20 on 2025-03-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_monthlyeconomicindicator_annualeconomicindicator'),
        ('myapp', '0004_merge_0002_currencynews_0003_remove_currency_event'),
    ]

    operations = [
    ]
