# Generated by Django 4.2.20 on 2025-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20250320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyeconomicindicator',
            name='federal_funds_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyeconomicindicator',
            name='treasury_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyeconomicindicator',
            name='unemployment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
