# Generated by Django 4.2.20 on 2025-04-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_anomalydetectionresult_currency_exchangeratecache_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRateCache',
        ),
    ]
