# Generated by Django 4.2.20 on 2025-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_currency_delete_exchangeratecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('lookback_days', models.IntegerField(default=90)),
                ('exchange_news_correlation', models.JSONField(default=dict)),
                ('exchange_economic_correlation', models.JSONField(default=dict)),
                ('volatility_news_correlation', models.JSONField(default=dict)),
                ('top_influencing_factors', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('data_completeness', models.FloatField()),
            ],
            options={
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='correlation_currency_pair_idx'), models.Index(fields=['analysis_date'], name='correlation_date_idx')],
                'unique_together': {('base_currency', 'target_currency', 'analysis_date')},
            },
        ),
    ]
