# Generated by Django 4.2.20 on 2025-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_correlationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationresult',
            name='volatility_economic_correlation',
            field=models.JSONField(default=dict),
        ),
    ]
