# Generated by Django 4.2.20 on 2025-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_correlationresult_volatility_economic_correlation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('forecast_horizon', models.IntegerField(help_text='Number of days ahead for the prediction')),
                ('mean_predictions', models.JSONField(default=dict, help_text='Mean predictions for each forecasted day')),
                ('lower_bound', models.JSONField(default=dict, help_text='Lower bound (10th percentile) for each forecasted day')),
                ('upper_bound', models.JSONField(default=dict, help_text='Upper bound (90th percentile) for each forecasted day')),
                ('model_version', models.CharField(help_text='Version of the model used', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the prediction')),
                ('input_data_range', models.CharField(help_text='Range of dates used for input data', max_length=100)),
                ('used_correlation_data', models.BooleanField(default=False, help_text='Whether correlation data was used')),
                ('used_news_sentiment', models.BooleanField(default=False, help_text='Whether news sentiment was used')),
                ('used_economic_indicators', models.BooleanField(default=False, help_text='Whether economic indicators were used')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='prediction_currency_pair_idx'), models.Index(fields=['prediction_date'], name='prediction_date_idx')],
                'unique_together': {('base_currency', 'target_currency', 'prediction_date', 'forecast_horizon')},
            },
        ),
    ]
