# Generated by Django 4.2.20 on 2025-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_currencyprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyprediction',
            name='change_percent',
            field=models.FloatField(default=0.0, help_text='Predicted percentage change from current rate'),
        ),
        migrations.AddField(
            model_name='currencyprediction',
            name='current_rate',
            field=models.FloatField(default=0.0, help_text='Current exchange rate at prediction time'),
        ),
    ]
