# Generated by Django 4.2.20 on 2025-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_currencyprediction_change_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyprediction',
            name='used_anomaly_detection',
            field=models.BooleanField(default=False, help_text='Whether anomaly detection was used in the prediction'),
        ),
    ]
