# Generated by Django 4.2.20 on 2025-04-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_currencyprediction_used_anomaly_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyprediction',
            name='mean_absolute_error',
            field=models.FloatField(blank=True, help_text='Mean absolute error of the prediction model', null=True),
        ),
        migrations.AddField(
            model_name='currencyprediction',
            name='mean_square_error',
            field=models.FloatField(blank=True, help_text='MSE of the prediction model', null=True),
        ),
        migrations.AddField(
            model_name='currencyprediction',
            name='root_mean_square_error',
            field=models.FloatField(blank=True, help_text='Root mean square error of the prediction model', null=True),
        ),
    ]
