name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t django-app:latest .

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run flake8 linting inside container
        run: |
          docker run --rm django-app:latest flake8 .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run unit tests inside container
        run: |
          docker-compose up -d
          docker-compose exec -T web python manage.py test
          docker-compose down

  integration-tests:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Placeholder for integration tests
        run: echo "Integration tests will be implemented later."

  notify:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Actions notification
        run: |
          if [ "$GITHUB_JOB" != "success" ]; then
            echo "Tests failed! Please check the workflow logs."
          fi
