name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t django-app .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run flake8 linting
        run: |
          docker run --rm django-app flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          docker-compose up -d
          docker-compose exec -T web python manage.py test
          docker-compose down

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests
        run: echo "Integration tests will be implemented later."

  notify:
    name: Notify on Failure
    needs: build
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send GitHub Notification
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              body: 'ERROR: Django CI/CD pipeline failed. Please check the logs and fix any issues.'
            })